#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Yamaguchi Yuto
# SPDX-License-Indentifer: BSD-3-Clause

import sys
import random

with open('dinner_list.txt', 'r', encoding='UTF-8') as f:
    data = f.read().split("\n")
    data_size = len(data)
    print(data[random.randrange(data_size-1)])
